spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: "200Mi"
          cpu: "2"
        requests:
          memory: "200Mi"
          cpu: "2"         #  #  CPU 资源的 requests 和 limits 设置为同一个相等的整数值。
