kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-rolebinding
  namespace: mynamespace
subjects:      # 被作用者
  - kind: User # 类型是 User，即 Kubernetes 里的用户。Kubernetes 里的“User”，也就是“用户”，只是一个授权系统里的逻辑概念
    name: example-user
    apiGroup: rbac.authorization.k8s.io
roleRef:       # RoleBinding 对象就可以直接通过名字，来引用我们前面定义的 Role 对象（example-role），从而定义了“被作用者（Subject）”和“角色（Role）”之间的绑定关系。
  kind: Role
  name: example-role
  apiGroup: rbac.authorization.k8s.io
