kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: mynamespace  # 它能产生作用的 Namepace 是 mynamespace
  name: example-role
rules:  #定义的权限规则
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]