apiVersion: v1
kind: Pod
metadata:
  namespace: mynamespace
  name: sa-token-test
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
  serviceAccountName: example-sa   # 定义Pod 要使用的要使用的 ServiceAccount 的名字是：example-sa
