apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: [ 'sh', '-c', 'echo Hello Kubernetes! && sleep 3600' ]
#  Istio 项目要做的，就是在这个 Pod YAML 被提交给 Kubernetes 之后，在它对应的 API 对象里自动加上
#  Envoy 容器的配置，使这个对象变成如下所示的样子
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: [ 'sh', '-c', 'echo Hello Kubernetes! && sleep 3600' ]
    #      这块是“自动注入”
    - name: envoy
      image: lyft/envoy:845747b88f102c0fd262ab234308e9e22f693a1
      command: [ "/usr/local/bin/envoy" ]
